//live api
export const MAIN_DOMAIN = "https://edrive.renrenfreshdelivery.com/api/";
export const PIC_URL = "https://edrive.renrenfreshdelivery.com/";

export const FETCH_DATA_START = "FETCH_DATA_START";
export const FETCH_ALL_DATA_START = "FETCH_ALL_DATA_START";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SIGNUPSUCCESS = "SIGNUPSUCCESS";
export const COACHSIGNUPSUCCESS = "COACHSIGNUPSUCCESS";


export const ADD_QUESTION_SUCCESS = "ADD_QUESTION_SUCCESS";
export const GET_QUESTION_SUCCESS = "GET_QUESTION_SUCCESS";
export const GET_EXAM_QUESTION_SUCCESS = "GET_EXAM_QUESTION_SUCCESS";

export const ADD_COMMON_REPLY_SUCCESS = "ADD_COMMON_REPLY_SUCCESS";
export const GET_COMMON_REPLY_SUCCESS = "GET_COMMON_REPLY_SUCCESS";

export const GET_BARRAGE_DATA_SUCCESS = "GET_BARRAGE_DATA_SUCCES";
export const ADD_BARRAGE_DATA_SUCCESS = "ADD_BARRAGE_DATA_SUCCESS";

export const GET_TRANSLATE_SUCCESS = "GET_TRANSLATE_SUCCESS";
export const ADD_TRANSLATE_SUCCESS = "ADD_TRANSLATE_SUCCESS";
export const FILL_TRANSLATE_SUCCESS = "FILL_TRANSLATE_SUCCESS";
export const FINISH_TRANSLATE_SUCCESS = "FINISH_TRANSLATE_SUCCESS";


export const GET_COURSE_SUCCESS = "GET_COURSE_SUCCESS";
export const ADD_COURSE_SUCCESS = "ADD_COURSE_SUCCESS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_STUDENT_USER_SUCCESS = "GET_STUDENT_USER_SUCCESS";
export const CHANGE_USER_SUCCESS = "CHANGE_USER_SUCCESS";
export const CHANGE_LICENSE_SUCCESS = "CHANGE_LICENSE_SUCCESS";
export const DEL_USER_SUCCESS = "DEL_USER_SUCCESS";


export const GET_RESERVATION_SUCCESS = "GET_RESERVATION_SUCCESS";
export const ADD_RESERVATION_SUCCESS = "ADD_RESERVATION_SUCCESS";
export const CHANGE_RESERVATION_SUCCESS = "CHANGE_RESERVATION_SUCCESS";

export const GET_TIME_SUCCESS = "GET_TIME_SUCCESS";
export const ADD_TIME_SUCCESS = "ADD_TIME_SUCCESS";
export const GET_STU_TIME_SUCCESS = "GET_STU_TIME_SUCCESS";
export const ADD_CLASS_SUCCESS = "ADD_CLASS_SUCCESS";

export const GET_COUPON_SUCCESS = "GET_COUPON_SUCCESS";
export const ADD_COUPON_SUCCESS = "ADD_COUPON_SUCCESS";

export const GET_RATE_SUCCESS = "GET_RATE_SUCCESS";
export const ADD_RATE_SUCCESS = "ADD_RATE_SUCCESS";

export const GET_LINK_SUCCESS = "GET_LINK_SUCCESS";
export const ADD_LINK_SUCCESS = "ADD_LINK_SUCCESS";

export const GET_COACH_SUCCESS = "GET_COACH_SUCCESS";
export const GET_COACH_LIST_SUCCESS = "GET_COACH_LIST_SUCCESS";
export const ADD_COACH_SUCCESS = "ADD_COACH_SUCCESS";
export const GET_COACH_BALANCE_SUCCESS = "GET_COACH_BALANCE_SUCCESS";

export const GET_STUDENT_SUCCESS = "GET_STUDENT_SUCCESS";
export const ADD_STUDENT_SUCCESS = "ADD_STUDENT_SUCCESS";

export const GET_EXAM_SUCCESS = "GET_EXAM_SUCCESS";
export const ADD_EXAM_SUCCESS = "ADD_EXAM_SUCCESS";

export const GET_VIDEO_SUCCESS = "GET_VIDEO_SUCCESS";
export const ADD_VIDEO_SUCCESS = "ADD_VIDEO_SUCCESS";

export const GET_WEBSITEINFO_SUCCESS = "GET_WEBSITEINFO_SUCCESS";
export const ADD_WEBSITEINFO_SUCCESS = "ADD_WEBSITEINFO_SUCCESS";

export const GET_MESSAGE_SUCCESS = "GET_MESSAGE_SUCCESS";
export const ADD_MESSAGE_SUCCESS = "ADD_MESSAGE_SUCCESS";

export const GET_PRICE_SUCCESS = "GET_PRICE_SUCCESS";
export const ADD_PRICE_SUCCESS = "ADD_PRICE_SUCCESS";

export const POP_UP_SIGNUP_ON = "POP_UP_SIGNUP_ON";
export const POP_UP_SIGNUP_OFF = "POP_UP_SIGNUP_OFF";

export const EMAIL_SEND_SUCCESS = "EMAIL_SEND_SUCCESS";
export const EMAIL_GET_SUCCESS = "EMAIL_GET_SUCCESS";








